#!/bin/bash
# Note:
# The variables inside _xxx_ are replaced by job_manager.py.

export OMP_NUM_THREADS=_OMP_NUM_THREADS_

CORES=_NUM_CORES_
INPUT=_INPUT_
OUTPUT=_OUTPUT_
PREOPTION=_PREOPTION_
POSTOPTION=_POSTOPTION_
BINARY=_BINARY_ROOT_/_BINARY_

$BINARY $PREOPTION < $INPUT $POSTOPTION > $OUTPUT
