[default] # queue-label
    # pre-defined variables
    mpi=true
    max_job_submit=1
    # other variables
    queue='small'
    num_cores=48
    omp_num_threads=1
    nodes=1
    cpns=48
    cores_per_node=48
    max_time='10:00:00'
